name: Release V2Ray-Desktop for Windows
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: windows-latest
    steps:
      # Install dependencies (MinGW)
      - name: Install MinGW compiler
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: x64
      # Install Qt
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '6.2.1'
          arch: 'win64_mingw81'
          install-deps: true
          target: desktop
      # Clone the source code
      - name: Get the source code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          submodules: true
      # Build
      - name: Build Binary
        run: |
          mkdir build
          cd build
          qmake ../src/V2Ray-Desktop.pro
          make -j16
          cd ..
          mkdir dist
          copy build/release/V2Ray-Desktop.exe dist
          windeployqt build/release/V2Ray-Desktop.exe --dir dist --release --qmldir src/ui
      # Localization
      - name: Localization
        run: |
          lrelease src/V2Ray-Desktop.pro
          mkdir dist/locales
          copy src/locales/*.qm dist/locales
      # Integrate with clash 1.9.0
      - name: Get clash-1.9.0
        uses: carlosperate/download-file-action@v1
        with:
          file-url: "https://github.com/Dreamacro/clash/releases/download/v1.9.0/clash-windows-amd64-v1.9.0.zip"
      - uses: carlosperate/download-file-action@v1
        with:
          file-url: "https://github.com/Dreamacro/maxmind-geoip/releases/latest/download/Country.mmdb"
      - run: |
          mkdir dist/clash-core
          unzip clash-windows-amd64-v1.9.0.zip
          move clash-windows-amd64.exe dist/clash-core/clash.exe
          move Country.mmdb dist/clash-core/Country.mmdb
      # Copy OpenSSL Dynamic Link Libraries
      - name: Fix OpenSSL
        uses: carlosperate/download-file-action@v1
        with:
          file-url: "https://github.com/Dr-Incognito/V2Ray-Desktop/files/7991307/libssl.dll%2Blibcrypto.dll.zip"
          file-name: "libssl.dll+libcrypto.dll.zip"
      - run: |
          unzip libssl.dll+libcrypto.dll.zip
          move libcrypto-1_1-x64.dll dist
          move libssl-1_1-x64.dll dist
      # Upload binaries to release
      - name: Create zip release
        uses: vimtor/action-zip@v1
        with:
          files: dist/
          dest: V2Ray-Desktop.zip
      - name: Upload Artifact
        uses: actions/upload-artifact@master
        with:
          name: V2Ray-Desktop-v${{ github.ref }}-win64.zip
          path: V2Ray-Desktop.zip
      - name: Upload binaries to release (Windows)
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: V2Ray-Desktop.zip
          asset_name: V2Ray-Desktop-v${{ github.ref }}-win64.zip
          tag: ${{ github.ref }}
          overwrite: true
